import { VideosResponse } from 'entities/video';

export const videos: VideosResponse = {
  items: [
    {
      kind: 'youtube#video',
      etag: 'oikjzuYBZ3WHu6uXs7wUrLuIXLE',
      id: 'eGV7zwjvxKs',
      snippet: {
        publishedAt: '2025-04-03T00:00:39Z',
        channelId: 'UCq0OueAsdxH6b8nyAspwViw',
        title: "Five Nights at Freddy's 2 | Official Teaser",
        description:
          'Welcome back! Are you ready to start the show? #FNAF2Movie only in theaters this December.\n\n--- \nAnyone can survive five nights. This time, there will be no second chances.\n\nBlumhouse’s box-office horror phenomenon Five Nights at Freddy’s, the highest-grossing horror film of 2023, begins a blood-chilling new chapter of animatronic terror.\n\nBased on Scott Cawthon’s blockbuster game series, Five Nights at Freddy’s 2 is directed by acclaimed returning filmmaker Emma Tammi (The Wind, Blood Moon).\n\nThe first film, which opened to a record-shattering $80 million and went on to earn almost $300 million worldwide, followed Mike, a troubled young man who reluctantly takes a job as a night security guard at an abandoned theme restaurant, Freddy\nFazbear’s Pizzeria, hoping it will help him retain custody of his young sister. That fateful decision instead drags him into the black heart of a supernatural nightmare. \n\nFive Nights at Freddy’s 2 is again produced by Jason Blum (M3GAN, Black Phone, Halloween franchise) and Scott Cawthon.\n\nFacebook: https://www.facebook.com/FNAFMovie/\nInstagram: https://www.instagram.com/fnafmovie\nX: https://x.com/FNAFMovie\nTikTok: https://www.tiktok.com/@fnafmovie\nfivenightsatfreddys.movie',
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/eGV7zwjvxKs/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/eGV7zwjvxKs/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/eGV7zwjvxKs/hqdefault.jpg',
            width: 480,
            height: 360,
          },
        },
        channelTitle: 'Universal Pictures',
        categoryId: '24',
        liveBroadcastContent: 'none',
        defaultLanguage: 'en-US',
        localized: {
          title: "Five Nights at Freddy's 2 | Official Teaser",
          description:
            'Welcome back! Are you ready to start the show? #FNAF2Movie only in theaters this December.\n\n--- \nAnyone can survive five nights. This time, there will be no second chances.\n\nBlumhouse’s box-office horror phenomenon Five Nights at Freddy’s, the highest-grossing horror film of 2023, begins a blood-chilling new chapter of animatronic terror.\n\nBased on Scott Cawthon’s blockbuster game series, Five Nights at Freddy’s 2 is directed by acclaimed returning filmmaker Emma Tammi (The Wind, Blood Moon).\n\nThe first film, which opened to a record-shattering $80 million and went on to earn almost $300 million worldwide, followed Mike, a troubled young man who reluctantly takes a job as a night security guard at an abandoned theme restaurant, Freddy\nFazbear’s Pizzeria, hoping it will help him retain custody of his young sister. That fateful decision instead drags him into the black heart of a supernatural nightmare. \n\nFive Nights at Freddy’s 2 is again produced by Jason Blum (M3GAN, Black Phone, Halloween franchise) and Scott Cawthon.\n\nFacebook: https://www.facebook.com/FNAFMovie/\nInstagram: https://www.instagram.com/fnafmovie\nX: https://x.com/FNAFMovie\nTikTok: https://www.tiktok.com/@fnafmovie\nfivenightsatfreddys.movie',
        },
        defaultAudioLanguage: 'en-US',
      },
      statistics: {
        viewCount: '6664636',
        likeCount: '488103',
        favoriteCount: '0',
        commentCount: '23842',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'Wygiht3utnvdsMa_gUY1VQjMA7Y',
      id: 'thyG51IdChc',
      snippet: {
        publishedAt: '2025-04-03T14:30:55Z',
        channelId: 'UCWzmOSSiSPbVnVu3ZAyDx2w',
        title:
          'Season 2: Hellfire Gala Official Trailer | Krakoa Welcomes You April 11! | Marvel Rivals',
        description:
          'Marvel Rivals Season 2: Hellfire Gala - Starts on April 11!\n \nIt’s the most glamorous night of the year, darling - Emma Frost herself invites you to the Hellfire Gala on Krakoa! 🌿💎 Once a year, this sovereign Mutant island opens its gates, welcoming both friend and rival alike to shape a brighter future. Now stranded in the year 2099 by a raging temporal storm, the fate of Krakoa hangs in the balance, its ecosystem suffering from dangerous chronal energy.\n \nCan a night of glittering festivities bring unity over fine dining and dazzling conversation? Who among the attendees possesses ulterior motives or solely seeks to party? And who is the uninvited guest?\n \nDress your best, step through the gates, and join us for an unforgettable evening of elegance, intrigue, and power.\n \n✨ The Hellfire Gala begins April 11th - don’t be fashionably late! ✨\n\nPlay Marvel Rivals FREE now: \n🔹 Steam: https://t.co/IPhy0Of1cG\n🔹 PlayStation: https://t.co/FR0aVfTmcn\n🔹 Xbox: https://t.co/GaAYz7Nku6\n🔹 Epic Games: https://t.co/QXoxz0VAP7\n \nFollow #MarvelRivals for updates: \n🔹 Discord: https://discord.gg/marvelrivals\n🔹 Twitter: https://twitter.com/MarvelRivals\n🔹 Instagram: https://www.instagram.com/marvelrivals/\n🔹 Facebook: https://www.facebook.com/marvelrivals/\n🔹 Tiktok: https://www.tiktok.com/@marvelrivals\n🔹Bluesky: https://bsky.app/profile/marvelrivalsglobal.bsky.social\n🔹Threads: https://www.threads.net/@marvelrivals\n🔹 Twitch: https://www.twitch.tv/marvelrivals\n \n#MarvelRivals #HellfireGala #Krakoa #EmmaFrost #Ultron',
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/thyG51IdChc/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/thyG51IdChc/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/thyG51IdChc/hqdefault.jpg',
            width: 480,
            height: 360,
          },
        },
        channelTitle: 'Marvel Rivals',
        tags: [
          'Marvel Rivals',
          'Season 2 Marvel Rivals',
          'FPS',
          'Hero Shooter',
          'Marvel',
          'Marvel Game',
        ],
        categoryId: '20',
        liveBroadcastContent: 'none',
        localized: {
          title:
            'Season 2: Hellfire Gala Official Trailer | Krakoa Welcomes You April 11! | Marvel Rivals',
          description:
            'Marvel Rivals Season 2: Hellfire Gala - Starts on April 11!\n \nIt’s the most glamorous night of the year, darling - Emma Frost herself invites you to the Hellfire Gala on Krakoa! 🌿💎 Once a year, this sovereign Mutant island opens its gates, welcoming both friend and rival alike to shape a brighter future. Now stranded in the year 2099 by a raging temporal storm, the fate of Krakoa hangs in the balance, its ecosystem suffering from dangerous chronal energy.\n \nCan a night of glittering festivities bring unity over fine dining and dazzling conversation? Who among the attendees possesses ulterior motives or solely seeks to party? And who is the uninvited guest?\n \nDress your best, step through the gates, and join us for an unforgettable evening of elegance, intrigue, and power.\n \n✨ The Hellfire Gala begins April 11th - don’t be fashionably late! ✨\n\nPlay Marvel Rivals FREE now: \n🔹 Steam: https://t.co/IPhy0Of1cG\n🔹 PlayStation: https://t.co/FR0aVfTmcn\n🔹 Xbox: https://t.co/GaAYz7Nku6\n🔹 Epic Games: https://t.co/QXoxz0VAP7\n \nFollow #MarvelRivals for updates: \n🔹 Discord: https://discord.gg/marvelrivals\n🔹 Twitter: https://twitter.com/MarvelRivals\n🔹 Instagram: https://www.instagram.com/marvelrivals/\n🔹 Facebook: https://www.facebook.com/marvelrivals/\n🔹 Tiktok: https://www.tiktok.com/@marvelrivals\n🔹Bluesky: https://bsky.app/profile/marvelrivalsglobal.bsky.social\n🔹Threads: https://www.threads.net/@marvelrivals\n🔹 Twitch: https://www.twitch.tv/marvelrivals\n \n#MarvelRivals #HellfireGala #Krakoa #EmmaFrost #Ultron',
        },
        defaultAudioLanguage: 'en',
      },
      statistics: {
        viewCount: '1548787',
        likeCount: '99327',
        favoriteCount: '0',
        commentCount: '7004',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'oN_Xk7OWZ4wno3W53dFIMYfnSNg',
      id: 'VuIiDjXRF5c',
      snippet: {
        publishedAt: '2025-04-03T05:13:06Z',
        channelId: 'UCJHAT3Uvv-g3I8H3GhHWV7w',
        title:
          'The April 2-3, 2025 Tornado Outbreak, As It Happened... (PART 1)',
        description:
          "Free Live 24/7 Weather Radar And Alerts: https://www.youtube.com/live/SFcykaD6g0M\n \n🔔 SUBSCRIBE and turn on notifications to stay informed about developing weather situations!\n\n⚠️ PLEASE NOTE: This video is meant to supplement official forecasts from the National Weather Service. Always follow forecasts and warnings from local officials.\n\n🌪️ Y'ALL SQUAD DISASTER RELIEF:\nLearn more about our nonprofit organization helping communities affected by severe weather: https://theyallsquad.org  \n\n🛒 SHOP:\nWeather radios, Y'all-O-Meters, and more at https://shopryanhall.com  \n\n#weatherchannel #ryanhall #ryanhallyall\n\nJoin this channel to get access to exclusive perks:\nhttps://www.youtube.com/channel/UCJHAT3Uvv-g3I8H3GhHWV7w/join\n\nSubscribe to these other channels:\nRyan Hall, Y'all XTRA: https://www.youtube.com/@RyanHallYallXTRA\nY'all Squad: https://www.youtube.com/@YallSquad\nMeteorologist Andy Hill: https://www.youtube.com/@metandyhill\n\nCheck out the Y'all Squad discord server!\nhttps://discord.gg/ryanhallyall\n\n📱 FOLLOW FOR UPDATES:\nhttps://www.facebook.com/ryanhallyall\nhttps://twitter.com/ryanhallyall\nhttps://www.instagram.com/ryanhallyall/\nhttps://www.tiktok.com/@ryanhallyall\nhttps://www.twitch.tv/ryanhallyall\n\nOFFICIAL WEBSITE: https://ryanhallyall.com/\n\nBUSINESS INQUIRIES: info@ryanhallyall.com\n\nRyan's PO Box\nPO Box 2668\nPikeville, KY 41501\n\nThe Y'all Squad PO Box\nPO Box 3068 \nPikeville, KY 41501\n\nPlease refer to your local National Weather Service office to get the most reliable and up to date weather information as possible.",
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/VuIiDjXRF5c/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/VuIiDjXRF5c/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/VuIiDjXRF5c/hqdefault.jpg',
            width: 480,
            height: 360,
          },
        },
        channelTitle: "Ryan Hall, Y'all",
        tags: [
          'weather',
          'weather forecasting',
          'forecasting',
          'forecast',
          'wild weather',
          'extreme weather',
          'intense weather',
          'beautiful weather',
          'weather channel',
          'weather hunter',
          'severe weather',
          'major',
          'intense',
          'extreme',
          'historic',
          'blizzard',
          'snow',
          'heavy snow',
          'major snow storm',
          'snowstorm',
          'snow squall',
          'one foot snow',
          'two feet snow',
          'winter storm',
          'tornado',
          'tornado chasing',
          'tornado chasers',
          'storm chasing',
          'storm chasers',
          'tornadoes',
          'ef5',
          'hurricane',
          'major hurricane',
          'ryan hall',
        ],
        categoryId: '25',
        liveBroadcastContent: 'none',
        defaultLanguage: 'en-US',
        localized: {
          title:
            'The April 2-3, 2025 Tornado Outbreak, As It Happened... (PART 1)',
          description:
            "Free Live 24/7 Weather Radar And Alerts: https://www.youtube.com/live/SFcykaD6g0M\n \n🔔 SUBSCRIBE and turn on notifications to stay informed about developing weather situations!\n\n⚠️ PLEASE NOTE: This video is meant to supplement official forecasts from the National Weather Service. Always follow forecasts and warnings from local officials.\n\n🌪️ Y'ALL SQUAD DISASTER RELIEF:\nLearn more about our nonprofit organization helping communities affected by severe weather: https://theyallsquad.org  \n\n🛒 SHOP:\nWeather radios, Y'all-O-Meters, and more at https://shopryanhall.com  \n\n#weatherchannel #ryanhall #ryanhallyall\n\nJoin this channel to get access to exclusive perks:\nhttps://www.youtube.com/channel/UCJHAT3Uvv-g3I8H3GhHWV7w/join\n\nSubscribe to these other channels:\nRyan Hall, Y'all XTRA: https://www.youtube.com/@RyanHallYallXTRA\nY'all Squad: https://www.youtube.com/@YallSquad\nMeteorologist Andy Hill: https://www.youtube.com/@metandyhill\n\nCheck out the Y'all Squad discord server!\nhttps://discord.gg/ryanhallyall\n\n📱 FOLLOW FOR UPDATES:\nhttps://www.facebook.com/ryanhallyall\nhttps://twitter.com/ryanhallyall\nhttps://www.instagram.com/ryanhallyall/\nhttps://www.tiktok.com/@ryanhallyall\nhttps://www.twitch.tv/ryanhallyall\n\nOFFICIAL WEBSITE: https://ryanhallyall.com/\n\nBUSINESS INQUIRIES: info@ryanhallyall.com\n\nRyan's PO Box\nPO Box 2668\nPikeville, KY 41501\n\nThe Y'all Squad PO Box\nPO Box 3068 \nPikeville, KY 41501\n\nPlease refer to your local National Weather Service office to get the most reliable and up to date weather information as possible.",
        },
        defaultAudioLanguage: 'en-US',
      },
      statistics: {
        viewCount: '5568851',
        likeCount: '76827',
        favoriteCount: '0',
        commentCount: '627',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'ErdGp24iLez2i7M9_z08pKatAPU',
      id: 'VrTVeYm4iIM',
      snippet: {
        publishedAt: '2025-04-02T14:03:52Z',
        channelId: 'UCGIY_O-8vW4rfX98KlMkvRg',
        title: 'Nintendo Direct: Nintendo Switch 2 – 4.2.2025',
        description:
          'Join us for a closer look at Nintendo Switch 2 in the Nintendo Direct: Nintendo Switch 2 – 4.2.2025 presentation.\n\nLearn more: https://www.nintendo.com/us/gaming-systems/switch-2/?utm_source=HW&utm_medium=soytnoa&utm_campaign=S1001-01&utm_id=S1001-01&utm_content=vod\n\n#NintendoSwitch2 #NintendoDirect\n\nVisit Nintendo.com for more info: https://www.nintendo.com/us/\n\nSubscribe for more Nintendo fun: https://goo.gl/HYYsot\n\nFollow Nintendo of America\nX/Twitter: https://twitter.com/NintendoAmerica\nFacebook: https://www.facebook.com/NintendoAmerica\nInstagram: https://www.instagram.com/nintendoamerica\nTwitch: https://www.twitch.tv/nintendo',
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/VrTVeYm4iIM/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/VrTVeYm4iIM/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/VrTVeYm4iIM/hqdefault.jpg',
            width: 480,
            height: 360,
          },
        },
        channelTitle: 'Nintendo of America',
        tags: [
          'nintendo',
          'game',
          'gameplay',
          'fun',
          'video game',
          'action',
          'adventure',
          'rpg',
          'play',
          'switch',
          'nintendo switch',
        ],
        categoryId: '20',
        liveBroadcastContent: 'none',
        localized: {
          title: 'Nintendo Direct: Nintendo Switch 2 – 4.2.2025',
          description:
            'Join us for a closer look at Nintendo Switch 2 in the Nintendo Direct: Nintendo Switch 2 – 4.2.2025 presentation.\n\nLearn more: https://www.nintendo.com/us/gaming-systems/switch-2/?utm_source=HW&utm_medium=soytnoa&utm_campaign=S1001-01&utm_id=S1001-01&utm_content=vod\n\n#NintendoSwitch2 #NintendoDirect\n\nVisit Nintendo.com for more info: https://www.nintendo.com/us/\n\nSubscribe for more Nintendo fun: https://goo.gl/HYYsot\n\nFollow Nintendo of America\nX/Twitter: https://twitter.com/NintendoAmerica\nFacebook: https://www.facebook.com/NintendoAmerica\nInstagram: https://www.instagram.com/nintendoamerica\nTwitch: https://www.twitch.tv/nintendo',
        },
        defaultAudioLanguage: 'en',
      },
      statistics: {
        viewCount: '5877087',
        likeCount: '207353',
        favoriteCount: '0',
        commentCount: '27794',
      },
    },
    {
      kind: 'youtube#video',
      etag: '7g1Ay4hd1FaeRyyrXOFET-yKgTs',
      id: 'IYLHdEzsk1s',
      snippet: {
        publishedAt: '2025-04-03T15:00:03Z',
        channelId: 'UCq0OueAsdxH6b8nyAspwViw',
        title: 'M3GAN 2.0 Official Trailer',
        description:
          'oops! she did it again!\n#M3GAN2 is only in theaters June 27. \n\n---\nWebsite: http://www.M3GANmovie.com\nYouTube: https://www.youtube.com/universalpictures  \nFacebook: https://www.facebook.com/meetM3GAN/\nX: https://twitter.com/meetm3gan\nInstagram: https://www.instagram.com/M3GAN/\nTikTok: https://www.tiktok.com/m3gan\n\n\nThe murderous doll who captivated pop culture in 2023 is back. And this time she’s not alone. \n\nThe original creative team behind that phenomenon—led by horror titans James Wan for Atomic Monster, Jason Blum for Blumhouse and writer-director Gerard Johnstone—reboot an all-new wild chapter in A.I. mayhem with M3GAN 2.0. Two years after M3GAN, a marvel of artificial intelligence, went rogue and embarked on\na murderous (and impeccably choreographed) rampage and was subsequently\ndestroyed, M3GAN’s creator Gemma (Allison Williams) has become a high-profile author and advocate for government oversight of A.I. Meanwhile, Gemma’s niece Cady (Violet McGraw), now 14, has become a teenager, rebelling against Gemma’s overprotective rules.\n\nUnbeknownst to them, the underlying tech for M3GAN has been stolen and misused by a powerful defense contractor to create a military-grade weapon known as Amelia (Ivanna Sakhno; Ahsoka, Pacific Rim: Uprising), the ultimate killer infiltration spy. But as Amelia’s self-awareness increases, she becomes decidedly less interested in taking orders from humans. Or in keeping them around. \n\nWith the future of human existence on the line, Gemma realizes that the only option is to resurrect M3GAN (Amie Donald, voiced by Jenna Davis) and give her a few upgrades, making her faster, stronger, and more lethal. As their paths collide, the original A.I icon is about to meet her match.\n\nM3GAN 2.0 is written and directed by acclaimed returning filmmaker Gerard Johnstone, from a story by Gerard Johnstone and Akela Cooper, based on characters created by Akela Cooper & James Wan.\n\nThe film co-stars returning cast members Brian Jordan Alvarez and Jen Van Epps as Gemma’s loyal tech teammates, Cole and Tess, and new characters played by Aristotle Athari (Saturday Night Live, Hacks), Timm Sharp (Apples Never Fall, Percy Jackson and the Olympians) and Grammy winner and 11-time Emmy nominee Jemaine Clement (Avatar: The Way of Water, What We Do in the Shadows). \n\nProduced by James Wan, Jason Blum and Allison Williams, the film is executive produced by Gerard Johnstone, Adam Hendricks, Greg Gilreath, Michael Clear, Judson Scott and Mark D. Katchur. \n\nThe first M3GAN film shattered box office records, opening to $30.4 million domestically to become the biggest opening weekend for a PG-13 horror film since A Quiet Place Part II. The film went on to gross more than $180 million worldwide.',
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/IYLHdEzsk1s/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/IYLHdEzsk1s/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/IYLHdEzsk1s/hqdefault.jpg',
            width: 480,
            height: 360,
          },
        },
        channelTitle: 'Universal Pictures',
        categoryId: '24',
        liveBroadcastContent: 'none',
        defaultLanguage: 'en-US',
        localized: {
          title: 'M3GAN 2.0 Official Trailer',
          description:
            'oops! she did it again!\n#M3GAN2 is only in theaters June 27. \n\n---\nWebsite: http://www.M3GANmovie.com\nYouTube: https://www.youtube.com/universalpictures  \nFacebook: https://www.facebook.com/meetM3GAN/\nX: https://twitter.com/meetm3gan\nInstagram: https://www.instagram.com/M3GAN/\nTikTok: https://www.tiktok.com/m3gan\n\n\nThe murderous doll who captivated pop culture in 2023 is back. And this time she’s not alone. \n\nThe original creative team behind that phenomenon—led by horror titans James Wan for Atomic Monster, Jason Blum for Blumhouse and writer-director Gerard Johnstone—reboot an all-new wild chapter in A.I. mayhem with M3GAN 2.0. Two years after M3GAN, a marvel of artificial intelligence, went rogue and embarked on\na murderous (and impeccably choreographed) rampage and was subsequently\ndestroyed, M3GAN’s creator Gemma (Allison Williams) has become a high-profile author and advocate for government oversight of A.I. Meanwhile, Gemma’s niece Cady (Violet McGraw), now 14, has become a teenager, rebelling against Gemma’s overprotective rules.\n\nUnbeknownst to them, the underlying tech for M3GAN has been stolen and misused by a powerful defense contractor to create a military-grade weapon known as Amelia (Ivanna Sakhno; Ahsoka, Pacific Rim: Uprising), the ultimate killer infiltration spy. But as Amelia’s self-awareness increases, she becomes decidedly less interested in taking orders from humans. Or in keeping them around. \n\nWith the future of human existence on the line, Gemma realizes that the only option is to resurrect M3GAN (Amie Donald, voiced by Jenna Davis) and give her a few upgrades, making her faster, stronger, and more lethal. As their paths collide, the original A.I icon is about to meet her match.\n\nM3GAN 2.0 is written and directed by acclaimed returning filmmaker Gerard Johnstone, from a story by Gerard Johnstone and Akela Cooper, based on characters created by Akela Cooper & James Wan.\n\nThe film co-stars returning cast members Brian Jordan Alvarez and Jen Van Epps as Gemma’s loyal tech teammates, Cole and Tess, and new characters played by Aristotle Athari (Saturday Night Live, Hacks), Timm Sharp (Apples Never Fall, Percy Jackson and the Olympians) and Grammy winner and 11-time Emmy nominee Jemaine Clement (Avatar: The Way of Water, What We Do in the Shadows). \n\nProduced by James Wan, Jason Blum and Allison Williams, the film is executive produced by Gerard Johnstone, Adam Hendricks, Greg Gilreath, Michael Clear, Judson Scott and Mark D. Katchur. \n\nThe first M3GAN film shattered box office records, opening to $30.4 million domestically to become the biggest opening weekend for a PG-13 horror film since A Quiet Place Part II. The film went on to gross more than $180 million worldwide.',
        },
        defaultAudioLanguage: 'en-US',
      },
      statistics: {
        viewCount: '1576162',
        likeCount: '77771',
        favoriteCount: '0',
        commentCount: '7694',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'lx8j2y1qS_sSpgbRj3NQRGm6_9Q',
      id: '5-ZR6Fi2Orc',
      snippet: {
        publishedAt: '2025-04-03T09:01:08Z',
        channelId: 'UCooVYzDxdwTtGYAkcPmOgOw',
        title: 'WHICH SIDE ARE YOU ON? (Brawl Stars Animation)',
        description:
          "💥 Justice Smasher Bibi in the Brawl Pass\n⚡️ Injustice Smasher Bibi and Virtue Smasher Bibi +  Superhero Title in the Brawl Pass Plus\n🦹 6 Skins from the winners of the #SupercellMAKE Superheroes campaign will be released throughout the Season\n🤘 Lumi's in the Starr Road!\n\n#SuperBrawl\n\nDownload NOW!! ►► https://supr.cl/2K62CZG\nSubscribe!! ►► https://supr.cl/subscribe",
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/5-ZR6Fi2Orc/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/5-ZR6Fi2Orc/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/5-ZR6Fi2Orc/hqdefault.jpg',
            width: 480,
            height: 360,
          },
        },
        channelTitle: 'Brawl Stars',
        tags: [
          'brawl stars',
          'mobile game',
          'mobile strategy game',
          'mobile rpg',
          'mobile battle royale',
          'battle royale',
          'supercell game',
          'new season',
          'heroes',
          'villains',
          'brawl animation',
          'brawl stars animation',
          'brawl new season',
          'supercell make',
          'bibi',
        ],
        categoryId: '20',
        liveBroadcastContent: 'none',
        defaultLanguage: 'en',
        localized: {
          title: 'WHICH SIDE ARE YOU ON? (Brawl Stars Animation)',
          description:
            "💥 Justice Smasher Bibi in the Brawl Pass\n⚡️ Injustice Smasher Bibi and Virtue Smasher Bibi +  Superhero Title in the Brawl Pass Plus\n🦹 6 Skins from the winners of the #SupercellMAKE Superheroes campaign will be released throughout the Season\n🤘 Lumi's in the Starr Road!\n\n#SuperBrawl\n\nDownload NOW!! ►► https://supr.cl/2K62CZG\nSubscribe!! ►► https://supr.cl/subscribe",
        },
        defaultAudioLanguage: 'en',
      },
      statistics: {
        viewCount: '3215084',
        likeCount: '124304',
        favoriteCount: '0',
        commentCount: '7526',
      },
    },
    {
      kind: 'youtube#video',
      etag: '4cBtpT5DWJqIj9n293qBvVkb7Rg',
      id: 'wbzJB36Z1F4',
      snippet: {
        publishedAt: '2025-04-03T15:00:07Z',
        channelId: 'UChpKl3waLmccNeYH9LGYjUQ',
        title: 'Laufey - Silver Lining (Official Music Video)',
        description:
          "New single \"Silver Lining\" Out Today \n\nStream everywhere now: https://laufey.ffm.to/silverlining\n\nFollow Laufey:\nSpotify: https://laufey.ffm.to/spotifyplaylist\nTikTok: https://www.tiktok.com/@laufey\nInstagram: https://www.instagram.com/laufey/\nTwitter: https://twitter.com/laufey\nFacebook: https://www.facebook.com/laufeymusic/\nWebsite: https://laufeymusic.com\n\nDirector: Jason Lester\nCreative Director: Junia Lin\nEP/Producer:  LE Seydel \nProduction Company: Ted & Jane\nDP: Emerson Duggan\nProduction Designer: Natalie Falt\n\nProduction Manager: Caroline Gluck\nProduction Coordinator: Sivan Ambros\n1st AD: Matthew Martinik\n2nd AD:  Mallory Chevalier\n1st AC: Dan Muchnik\n2nd AC: Fred Porras\nLoader: Kate Ruthenbeck\nGaffer: Tate McCurdy\nACLT:  Clay Pacatte\nSLT/Driver: Mayur Patankar\nSLT: Wei \"Colvin\" Ang\nKey Grip: Tiger Whitesides\nGrip / Driver: Miles Schirra\nBBG: Daniel Kusenda\nGrip: Beau Beagles\nArt director Danelle Kaufman\nLeadman: Chris Roze\nSet Dresser: Camilo Castano\nSet Dresser: Mary Delioussina\nTruck PA: Gavin Sullivan\nSet PA: Matteo, Chris Zamora, Bryant Familla, Sawyer Staloch\nMedic: Rufino Rumero\n\nLaufey Makeup Artist: Heather Harris\nLaufey Hair: Kiley Fitzgerald\nLaufey Stylist: Leith Clark\nLaufey Stylist Asst: Abby Depass\nExtras Stylist: Lindsey Hartman\nExtra Stylist Asst: Sadie Spezzano\n\nMale Lead: Miles Robbins\nChoreographer: Masha Cherezova\nDancer: Enya Kollek\nDancer: Camila Arana\nDancer: Lydia Marie McDonald\nDancer: Colleen Marie Loverde\nDancer: Spencer Lenain\nDancer: Chadwick Gaspard\nDancer: Maxwell Simoes\nDancer: Hunter Wayne Foster\nDancer: Chandler Davids\n\nEditor: Jason Lester\nCo-Editor and FX: Blu Hunt\nColor Studio: Studio RM\nColorist: Myles Bevan \nColor EP: Mike Coley \nColor Producer: Paloma Bido\n\nVideo Commissioner: Bianca Bhagat for AWAL\nManager: Max Gredinger for Foundations\nDay-to-Day Manager: Jackie Karlsson for Foundations\nBTS: Jacq Justice\nDirectors Agent: Lark Creative / Cheyenne Cody\n\n\nLyrics: \nI've been falling in bad habits, staring into the abyss\nDrowning in red wine and sniffing cinnamon\n\nWe've been kissing on the playground, acting like little kids\nMaking dirty jokes and getting away with it\n\nSo I propose, it's long overdue\nWhen you go to hell, I'll go there with you too\nAnd when we're punished for being so cruel\nThe silver lining’s I'll be there with you\n\nNever been calm or collected,\nNo one ever called me sweet\nWhat a miracle I found a darling\n\nI met you at the worst time, fell in love on a whim\nNow we pirouette in fields of rosy sin\n\nSo I propose, it's long overdue\nWhen you go to hell, I'll go there with you too\nAnd when we're punished for being so cruel\nThe silver lining’s I'll be there with you\n\nThe silver lining’s I'll be there with you\n\n#Laufey #SilverLining",
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/wbzJB36Z1F4/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/wbzJB36Z1F4/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/wbzJB36Z1F4/hqdefault.jpg',
            width: 480,
            height: 360,
          },
          standard: {
            url: 'https://i.ytimg.com/vi/wbzJB36Z1F4/sddefault.jpg',
            width: 640,
            height: 480,
          },
          maxres: {
            url: 'https://i.ytimg.com/vi/wbzJB36Z1F4/maxresdefault.jpg',
            width: 1280,
            height: 720,
          },
        },
        channelTitle: 'Laufey',
        tags: [
          'newmusic',
          'laufey',
          'silverlining',
          'fromthestart',
          'ballet',
          'jazz',
          'new',
          'music',
          'silver',
          'lining',
          'silver lining laufey',
          'silver lining',
          'new song',
          'song',
          'album',
          'from the start',
          'coffee',
          'cool',
          'book club',
          'pop vocal',
          'pop',
        ],
        categoryId: '10',
        liveBroadcastContent: 'none',
        localized: {
          title: 'Laufey - Silver Lining (Official Music Video)',
          description:
            "New single \"Silver Lining\" Out Today \n\nStream everywhere now: https://laufey.ffm.to/silverlining\n\nFollow Laufey:\nSpotify: https://laufey.ffm.to/spotifyplaylist\nTikTok: https://www.tiktok.com/@laufey\nInstagram: https://www.instagram.com/laufey/\nTwitter: https://twitter.com/laufey\nFacebook: https://www.facebook.com/laufeymusic/\nWebsite: https://laufeymusic.com\n\nDirector: Jason Lester\nCreative Director: Junia Lin\nEP/Producer:  LE Seydel \nProduction Company: Ted & Jane\nDP: Emerson Duggan\nProduction Designer: Natalie Falt\n\nProduction Manager: Caroline Gluck\nProduction Coordinator: Sivan Ambros\n1st AD: Matthew Martinik\n2nd AD:  Mallory Chevalier\n1st AC: Dan Muchnik\n2nd AC: Fred Porras\nLoader: Kate Ruthenbeck\nGaffer: Tate McCurdy\nACLT:  Clay Pacatte\nSLT/Driver: Mayur Patankar\nSLT: Wei \"Colvin\" Ang\nKey Grip: Tiger Whitesides\nGrip / Driver: Miles Schirra\nBBG: Daniel Kusenda\nGrip: Beau Beagles\nArt director Danelle Kaufman\nLeadman: Chris Roze\nSet Dresser: Camilo Castano\nSet Dresser: Mary Delioussina\nTruck PA: Gavin Sullivan\nSet PA: Matteo, Chris Zamora, Bryant Familla, Sawyer Staloch\nMedic: Rufino Rumero\n\nLaufey Makeup Artist: Heather Harris\nLaufey Hair: Kiley Fitzgerald\nLaufey Stylist: Leith Clark\nLaufey Stylist Asst: Abby Depass\nExtras Stylist: Lindsey Hartman\nExtra Stylist Asst: Sadie Spezzano\n\nMale Lead: Miles Robbins\nChoreographer: Masha Cherezova\nDancer: Enya Kollek\nDancer: Camila Arana\nDancer: Lydia Marie McDonald\nDancer: Colleen Marie Loverde\nDancer: Spencer Lenain\nDancer: Chadwick Gaspard\nDancer: Maxwell Simoes\nDancer: Hunter Wayne Foster\nDancer: Chandler Davids\n\nEditor: Jason Lester\nCo-Editor and FX: Blu Hunt\nColor Studio: Studio RM\nColorist: Myles Bevan \nColor EP: Mike Coley \nColor Producer: Paloma Bido\n\nVideo Commissioner: Bianca Bhagat for AWAL\nManager: Max Gredinger for Foundations\nDay-to-Day Manager: Jackie Karlsson for Foundations\nBTS: Jacq Justice\nDirectors Agent: Lark Creative / Cheyenne Cody\n\n\nLyrics: \nI've been falling in bad habits, staring into the abyss\nDrowning in red wine and sniffing cinnamon\n\nWe've been kissing on the playground, acting like little kids\nMaking dirty jokes and getting away with it\n\nSo I propose, it's long overdue\nWhen you go to hell, I'll go there with you too\nAnd when we're punished for being so cruel\nThe silver lining’s I'll be there with you\n\nNever been calm or collected,\nNo one ever called me sweet\nWhat a miracle I found a darling\n\nI met you at the worst time, fell in love on a whim\nNow we pirouette in fields of rosy sin\n\nSo I propose, it's long overdue\nWhen you go to hell, I'll go there with you too\nAnd when we're punished for being so cruel\nThe silver lining’s I'll be there with you\n\nThe silver lining’s I'll be there with you\n\n#Laufey #SilverLining",
        },
        defaultAudioLanguage: 'en',
      },
      statistics: {
        viewCount: '311204',
        likeCount: '56060',
        favoriteCount: '0',
        commentCount: '4822',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'dJjK5l-TJ0DYb64ld5WDN-21OZA',
      id: 'jLpUEACVBlE',
      snippet: {
        publishedAt: '2025-04-02T20:41:01Z',
        channelId: 'UCK7tptUDHh-RYDsdxO1-5QQ',
        title:
          'Trump’s Auto Tariffs: We Broke Down an F-150 to Explain Industry Impact | WSJ',
        description:
          "President Trump says cars made in the U.S. will face “absolutely no tariff,” but it’s not so simple. No car is built from 100% U.S. parts—not even the U.S.-built Ford F-150 pickup truck. Major components of the car are from Mexico, Canada and South Korea, which could all be a part of the auto tariffs.\n\nWSJ takes a look inside a Ford F-150 to better understand Trump’s slew of new tariffs and why automakers are warning it could backfire. \n\nChapters:\n0:00 Trump’s auto tariffs\n0:53 Tariff breakdown of car parts\n4:12 Challenge of opening new plants\n5:32 Economic impact and broader threats\n\nNews Explainers\nSome days the high-speed news cycle can bring more questions than answers. WSJ’s news explainers break down the day's biggest stories into bite-size pieces to help you make sense of the news.\n\n#Trump #Cars #WSJ",
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/jLpUEACVBlE/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/jLpUEACVBlE/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/jLpUEACVBlE/hqdefault.jpg',
            width: 480,
            height: 360,
          },
          standard: {
            url: 'https://i.ytimg.com/vi/jLpUEACVBlE/sddefault.jpg',
            width: 640,
            height: 480,
          },
          maxres: {
            url: 'https://i.ytimg.com/vi/jLpUEACVBlE/maxresdefault.jpg',
            width: 1280,
            height: 720,
          },
        },
        channelTitle: 'The Wall Street Journal',
        tags: [
          'trump',
          'auto tariffs',
          'tariffs',
          'trade war',
          'trump tariffs',
          'trump news',
          'trump live',
          'trump auto tariffs',
          'f 150',
          'ford f150',
          'ford tariffs',
          'automobile',
          'car industry',
          'auto tariffs impact',
          'reciprocal tariffs',
          'mexico',
          'mexico tariffs',
          'canada',
          'canada tariffs',
          'south korea',
          'us manufacturing',
          'domestic production',
          'automakers',
          'car parts',
          'ford news',
          'tariff impact',
          'tariffs explained',
          'universal tariffs',
          'usmca',
          'trade agreement',
          'global trade',
          'china',
          'china trade war',
          'automobile industry',
          'usnews',
        ],
        categoryId: '25',
        liveBroadcastContent: 'none',
        defaultLanguage: 'en',
        localized: {
          title:
            'Trump’s Auto Tariffs: We Broke Down an F-150 to Explain Industry Impact | WSJ',
          description:
            "President Trump says cars made in the U.S. will face “absolutely no tariff,” but it’s not so simple. No car is built from 100% U.S. parts—not even the U.S.-built Ford F-150 pickup truck. Major components of the car are from Mexico, Canada and South Korea, which could all be a part of the auto tariffs.\n\nWSJ takes a look inside a Ford F-150 to better understand Trump’s slew of new tariffs and why automakers are warning it could backfire. \n\nChapters:\n0:00 Trump’s auto tariffs\n0:53 Tariff breakdown of car parts\n4:12 Challenge of opening new plants\n5:32 Economic impact and broader threats\n\nNews Explainers\nSome days the high-speed news cycle can bring more questions than answers. WSJ’s news explainers break down the day's biggest stories into bite-size pieces to help you make sense of the news.\n\n#Trump #Cars #WSJ",
        },
        defaultAudioLanguage: 'en',
      },
      statistics: {
        viewCount: '2465573',
        likeCount: '29921',
        favoriteCount: '0',
        commentCount: '7758',
      },
    },
    {
      kind: 'youtube#video',
      etag: '2BYmh9kp42of06QHoeX8DLWx58g',
      id: 'oUIK01ek-Ko',
      snippet: {
        publishedAt: '2025-04-02T15:59:49Z',
        channelId: 'UC7R27sAWc_DqOldtI1JcYhQ',
        title: 'South Park | Season 27 Teaser',
        description:
          'South Park returns with all-new episodes on Wednesday, July 9 to Comedy Central.',
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/oUIK01ek-Ko/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/oUIK01ek-Ko/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/oUIK01ek-Ko/hqdefault.jpg',
            width: 480,
            height: 360,
          },
          standard: {
            url: 'https://i.ytimg.com/vi/oUIK01ek-Ko/sddefault.jpg',
            width: 640,
            height: 480,
          },
          maxres: {
            url: 'https://i.ytimg.com/vi/oUIK01ek-Ko/maxresdefault.jpg',
            width: 1280,
            height: 720,
          },
        },
        channelTitle: 'South Park Studios',
        tags: [
          'cartman',
          'south park funniest moments',
          'south park (tv program)',
          'south park best moments',
          'south park funny moments',
          'south park full episodes',
          'south park episodes',
          'south park funniest',
          'funny',
          'comedy',
          'cartoon',
          'animation',
          'hd',
          'south park',
          'South Park | Season 27 Teaser',
          'south park season 27',
          'South Park season 27',
          'south park season 27 full episodes',
          'south park new trailer',
          'south park season 27 trailer',
          'south park season 27 teaser',
          'south park season 27 new trailer',
          'south park show',
        ],
        categoryId: '23',
        liveBroadcastContent: 'none',
        localized: {
          title: 'South Park | Season 27 Teaser',
          description:
            'South Park returns with all-new episodes on Wednesday, July 9 to Comedy Central.',
        },
        defaultAudioLanguage: 'en',
      },
      statistics: {
        viewCount: '1121211',
        likeCount: '58307',
        favoriteCount: '0',
        commentCount: '6910',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'iaa71KqlyvnyLhnq1YfpIdfp2iM',
      id: '3yfg7wYZR5Q',
      snippet: {
        publishedAt: '2025-04-03T04:59:28Z',
        channelId: 'UCMUP9j-QidC_S0KLlO06uCg',
        title:
          '"SHATTERED VEIL" EASTER EGG GUIDE! - FULL EASTER EGG TUTORIAL (Black Ops 6 Zombies Easter Egg)',
        description:
          "BLACK OPS 6 ZOMBIES SHATTERED VEIL EASTER EGG GUIDE: FULL WALKTHROUGH!\n►If you enjoyed the video, please consider hitting 👍 LIKE and ✅ Subscribe for more!\n►Full Ending: https://youtu.be/6VRR2M5ISYk\n\nIn this video, I am showing you how to complete the Shattered Veil Easter Egg. Giving you a full Shattered Veil Easter Egg Guide on how to complete the Black Ops 6 Zombies Shattered Veil Tutorial going over all Shattered Veil Easter Egg Steps and full Black Ops 6 Zombies Easter Egg Completion. This is the Black Ops 6 Zombies Shattered Veil Easter Egg with Shattered Veil Boss Fight & Shattered Veil Ending Cutscene. This is a FULL Shattered Veil Easter Egg Guide, including all Shattered Veil Easter Egg Steps with Shattered Veil Easter Egg Boss Fight. Black Ops 6 Zombies Shattered Veil Easter Egg Guide - Full Shattered Veil Easter Egg Walkthrough Tutorial! \n\n➖ Follow me! ➖\n🐥 Twitter - http://www.twitter.com/MrDalekJD\n📘 Facebook - http://facebook.com/MrDalekJD\n📸 Instagram - http://instagram.com/MrDalekJD\n🚨Second Channel - https://www.youtube.com/channel/UCmn6qb15MOEDxa8DyqxIzhQ\n👾 Join the MrDalekJD Discord - https://discord.gg/Wc28nWzkmB\n\n➖ The equipment I use! ➖\n🎧 The headset I use - https://astro.family/mrdalekjdEMEA\n\nSubscribe for more videos!\n- MrDalekJD\n\nBusiness Enquiries: business@mrdalekjd.com\n\nLet's keep the comment section AWESOME to make sure everyone has a good time! Be sure to thumbs up great comments and ignore negative or hateful ones. Thanks and enjoy!\n\nIf you enjoyed the video & want to see more Call of Duty, press that Like button!\n\n#BlackOps6Zombies #BlackOps6 #CallofDuty #callofdutyzombies\n\nBLACK OPS 6 ZOMBIES SHATTERED VEIL EASTER EGG GUIDE! (FULL BO6 ZOMBIES EASTER EGG WALKTHROUGH)",
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/3yfg7wYZR5Q/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/3yfg7wYZR5Q/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/3yfg7wYZR5Q/hqdefault.jpg',
            width: 480,
            height: 360,
          },
          standard: {
            url: 'https://i.ytimg.com/vi/3yfg7wYZR5Q/sddefault.jpg',
            width: 640,
            height: 480,
          },
          maxres: {
            url: 'https://i.ytimg.com/vi/3yfg7wYZR5Q/maxresdefault.jpg',
            width: 1280,
            height: 720,
          },
        },
        channelTitle: 'MrDalekJD',
        tags: [
          'shattered veil easter egg',
          'shattered veil easter egg guide',
          'black ops 6 zombies shattered veil',
          'black ops 6 zombies shattered veil easter egg guide',
          'black ops 6 zombies shattered veil easter egg',
          'shattered veil easter egg steps',
          'shattered veil',
          'zombies easter egg guide',
          'shattered veil guide',
          'shattered veil zombies easter egg',
          'shattered veil easter egg full guide',
          'shattered veil easter egg tutorial',
          'black ops 6 zombies easter egg guide',
          'bo6 shattered veil easter egg',
        ],
        categoryId: '20',
        liveBroadcastContent: 'none',
        localized: {
          title:
            '"SHATTERED VEIL" EASTER EGG GUIDE! - FULL EASTER EGG TUTORIAL (Black Ops 6 Zombies Easter Egg)',
          description:
            "BLACK OPS 6 ZOMBIES SHATTERED VEIL EASTER EGG GUIDE: FULL WALKTHROUGH!\n►If you enjoyed the video, please consider hitting 👍 LIKE and ✅ Subscribe for more!\n►Full Ending: https://youtu.be/6VRR2M5ISYk\n\nIn this video, I am showing you how to complete the Shattered Veil Easter Egg. Giving you a full Shattered Veil Easter Egg Guide on how to complete the Black Ops 6 Zombies Shattered Veil Tutorial going over all Shattered Veil Easter Egg Steps and full Black Ops 6 Zombies Easter Egg Completion. This is the Black Ops 6 Zombies Shattered Veil Easter Egg with Shattered Veil Boss Fight & Shattered Veil Ending Cutscene. This is a FULL Shattered Veil Easter Egg Guide, including all Shattered Veil Easter Egg Steps with Shattered Veil Easter Egg Boss Fight. Black Ops 6 Zombies Shattered Veil Easter Egg Guide - Full Shattered Veil Easter Egg Walkthrough Tutorial! \n\n➖ Follow me! ➖\n🐥 Twitter - http://www.twitter.com/MrDalekJD\n📘 Facebook - http://facebook.com/MrDalekJD\n📸 Instagram - http://instagram.com/MrDalekJD\n🚨Second Channel - https://www.youtube.com/channel/UCmn6qb15MOEDxa8DyqxIzhQ\n👾 Join the MrDalekJD Discord - https://discord.gg/Wc28nWzkmB\n\n➖ The equipment I use! ➖\n🎧 The headset I use - https://astro.family/mrdalekjdEMEA\n\nSubscribe for more videos!\n- MrDalekJD\n\nBusiness Enquiries: business@mrdalekjd.com\n\nLet's keep the comment section AWESOME to make sure everyone has a good time! Be sure to thumbs up great comments and ignore negative or hateful ones. Thanks and enjoy!\n\nIf you enjoyed the video & want to see more Call of Duty, press that Like button!\n\n#BlackOps6Zombies #BlackOps6 #CallofDuty #callofdutyzombies\n\nBLACK OPS 6 ZOMBIES SHATTERED VEIL EASTER EGG GUIDE! (FULL BO6 ZOMBIES EASTER EGG WALKTHROUGH)",
        },
        defaultAudioLanguage: 'en-US',
      },
      statistics: {
        viewCount: '244664',
        likeCount: '6632',
        favoriteCount: '0',
        commentCount: '503',
      },
    },
  ],
  nextPageToken: 'CAoQAA',
  pageInfo: {
    totalResults: 200,
    resultsPerPage: 10,
  },
};
