import {
  ArrowFallIcon,
  ArrowGrowIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  CheckedIcon,
  CloseIcon,
  ExitIcon,
  FilterIcon,
  HomeIcon,
  MenuIcon,
  NoIcon,
  SearchIcon,
  SortASCIcon,
  SortDESCIcon,
  SpinnerIcon,
  UncheckedIcon,
  VideosIcon,
  YesIcon,
} from './Icons';

export const Icons = {
  search: SearchIcon,
  home: HomeIcon,
  videos: VideosIcon,
  arrowLeft: ArrowLeftIcon,
  arrowRight: ArrowRightIcon,
  yesIcon: YesIcon,
  noIcon: NoIcon,
  spinner: SpinnerIcon,
  arrowGrow: ArrowGrowIcon,
  arrowFall: ArrowFallIcon,
  exit: ExitIcon,
  sortASC: SortASCIcon,
  sortDESC: SortDESCIcon,
  filter: FilterIcon,
  checked: CheckedIcon,
  unchecked: UncheckedIcon,
  menu: MenuIcon,
  close: CloseIcon
};
